version: 2

before:
  hooks:
  - go mod tidy

builds:
- env: [ CGO_ENABLED=0 ]
  binary: server

checksum:
  name_template: 'checksums.txt'

dockers:
- dockerfile: build.Dockerfile
  image_templates:
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-amd64'
  use: buildx
  goos: linux
  goarch: amd64
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--platform=linux/amd64"
- dockerfile: build.Dockerfile
  image_templates:
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-arm64'
  use: buildx
  goos: linux
  goarch: arm64
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--platform=linux/arm64"
- dockerfile: build.Dockerfile
  image_templates:
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-386'
  use: buildx
  goos: linux
  goarch: '386'
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--platform=linux/386"

docker_manifests:
- name_template: 'w3irdrobot/voltageautounlock:{{ .Version }}'
  image_templates:
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-amd64'
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-arm64'
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-386'
- name_template: 'w3irdrobot/voltageautounlock:latest'
  image_templates:
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-amd64'
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-arm64'
  - 'w3irdrobot/voltageautounlock:{{ .Version }}-linux-386'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^Merge pull request'
    - 'typo'
    - 'version bump'
